"""Developer + analytics markdown report.

Complements the HTML analytics report with provenance (dataset params, models,
prompt version), step-by-step LLM validation results, and an improvement
snapshot — aimed at engineers iterating on the AI application.
"""
from __future__ import annotations

import platform
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config  # noqa: E402


def _pct(x) -> str:
    if x is None:
        return "n/a"
    return f"{100 * float(x):.1f}%"


def render(metrics: dict, run_meta: dict | None = None) -> str:
    run_meta = run_meta or {}
    ev = metrics.get("evaluation", {})
    det = ev.get("detection", {})
    sweep = ev.get("threshold_sweep", {})
    llm = ev.get("llm_output", {})
    steps = ev.get("llm_step_validation", {})
    improve = ev.get("llm_prompt_improvement", {})
    judge = ev.get("llm_as_judge", {})
    sup = metrics.get("supervisory", {})
    totals = sup.get("totals", {})
    drift = metrics.get("drift", {})

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# SupTech-XAI — Developer & Analytics Report",
        "",
        f"_Generated {now}_",
        "",
        "This report combines **model-risk analytics** with **developer "
        "provenance** for the LLM application (dataset, models, CoT prompt "
        "version, per-step validation, and prompt-structure improvement).",
        "",
        "See also: [`docs/LLM_AND_DATA.md`](../../docs/LLM_AND_DATA.md) "
        "(from `data/reports/`) or the same file at the repo root under `docs/`.",
        "",
        "## 1. Run provenance",
        "",
        "| Item | Value |",
        "|---|---|",
        f"| Dataflow | `{config.DATAFLOW_REF}` |",
        f"| Prompt version | `{config.PROMPT_VERSION}` |",
        f"| Explain model | `{config.OLLAMA_MODEL}` |",
        f"| Judge model | `{config.OLLAMA_JUDGE_MODEL}` |",
        f"| Anomaly sigma | `{config.ANOMALY_SIGMA}` |",
        f"| Python | `{platform.python_version()}` |",
    ]
    for k, v in run_meta.items():
        lines.append(f"| {k} | `{v}` |")
    lines += [
        "",
        "### Dataset (synthetic)",
        "",
        "Generated by `data_generator/kafka_producer.py` — SDMX banking "
        "submissions with seeded structural invalids and semantic anomalies. "
        "Defaults: **500** rows, **12%** invalid, **6%** anomaly, seed **42**. "
        "Ground truth for detector eval = membership of `TXN_PURPOSE` in "
        "`ANOMALOUS_PURPOSES`.",
        "",
        "## 2. Supervisory snapshot",
        "",
        "| KPI | Value |",
        "|---|---|",
        f"| Observations | {totals.get('observations', '-')} |",
        f"| Anomalies flagged | {totals.get('anomalies', '-')} |",
        f"| Anomaly rate | {_pct(totals.get('anomaly_rate'))} |",
        f"| Flagged value | {totals.get('flagged_value', 0):,.0f} |",
    ]
    gov = sup.get("governance", {})
    if gov:
        lines.append(f"| FMR rejection rate | {_pct(gov.get('rejection_rate'))} |")

    lines += [
        "",
        "## 3. Detector evaluation",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Precision | {det.get('precision', '-')} |",
        f"| Recall | {det.get('recall', '-')} |",
        f"| F1 | {det.get('f1', '-')} |",
        f"| Accuracy | {det.get('accuracy', '-')} |",
        f"| Support (true anomalies) | {det.get('support_anomalies', '-')} |",
    ]
    cm = det.get("confusion_matrix", {})
    if cm:
        lines += [
            "",
            "Confusion matrix: "
            f"TP={cm.get('tp')} FP={cm.get('fp')} FN={cm.get('fn')} TN={cm.get('tn')}",
        ]
    if sweep.get("best_operating_point"):
        b = sweep["best_operating_point"]
        lines += [
            "",
            f"F1-optimal operating point: **sigma={b.get('sigma')}** "
            f"(F1={b.get('f1')}); configured sigma={sweep.get('current_sigma')}.",
        ]

    lines += [
        "",
        "## 4. LLM application — output quality",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Explanations (n) | {llm.get('n', 0)} |",
        f"| Engines | {', '.join(llm.get('engines') or []) or '-'} |",
        f"| Prompt versions | {', '.join(llm.get('prompt_versions') or []) or '-'} |",
        f"| Models | {', '.join(llm.get('models') or []) or '-'} |",
        f"| Output validity | {_pct(llm.get('output_validity_rate'))} |",
        f"| Faithfulness recall | {_pct(llm.get('faithfulness_recall'))} |",
        f"| HIGH-rating precision | {_pct(llm.get('high_rating_precision'))} |",
        f"| Judge avg ( /5 ) | {judge.get('avg_score', '-')} "
        f"({judge.get('judge_engine', '')} / {judge.get('judge_model', '')}) |",
        "",
        "### Risk-rating distribution",
        "",
    ]
    for rating, count in (llm.get("rating_distribution") or {}).items():
        lines.append(f"- **{rating}**: {count}")

    lines += [
        "",
        "## 5. Step-by-step CoT validation",
        "",
        "Each explanation must satisfy the four-step contract "
        "(purpose vs asset class → amount → red flags → rating/action).",
        "",
        "| Check | Pass rate |",
        "|---|---|",
        f"| All four steps present | {_pct(steps.get('has_all_steps_rate'))} |",
        f"| STEP1 (purpose / asset) | {_pct(steps.get('step1_ok_rate'))} |",
        f"| STEP2 (amount) | {_pct(steps.get('step2_ok_rate'))} |",
        f"| STEP3 (red flags) | {_pct(steps.get('step3_ok_rate'))} |",
        f"| STEP4 (rating + action) | {_pct(steps.get('step4_ok_rate'))} |",
        f"| **All steps OK** | **{_pct(steps.get('all_steps_ok_rate'))}** |",
        "",
        f"Failures: **{steps.get('failure_count', 0)}** / {steps.get('n', 0)}",
        "",
    ]
    failures = steps.get("failures_sample") or []
    if failures:
        lines.append("Sample failures:")
        lines.append("")
        for f in failures[:10]:
            lines.append(
                f"- `{f.get('id')}` rating={f.get('rating')} "
                f"failed={', '.join(f.get('failed_checks') or [])}"
            )
        lines.append("")

    lines += [
        "## 6. Prompt improvement snapshot",
        "",
        "| Score | Value |",
        "|---|---|",
        f"| Current prompt | `{improve.get('current_prompt_version', config.PROMPT_VERSION)}` |",
        f"| v2 structure score | {improve.get('v2_structure_score', '-')} |",
        f"| v1 structure score | {improve.get('v1_structure_score', '-')} |",
        f"| Structure lift (v2 − v1) | {improve.get('structure_lift', '-')} |",
        "",
        improve.get("note", ""),
        "",
        "## 7. Drift (PSI)",
        "",
    ]
    if drift:
        for key, title in [
            ("predicted_category_psi", "Predicted category"),
            ("anomaly_score_psi", "Anomaly score"),
        ]:
            d = drift.get(key, {})
            lines.append(
                f"- **{title}**: PSI={d.get('psi', '-')} "
                f"band=`{d.get('band', 'n/a')}`"
            )
    else:
        lines.append("_No drift metrics available._")

    lines += [
        "",
        "## 8. Artefacts",
        "",
        f"- Metrics JSON: `{config.METRICS_JSON.relative_to(config.ROOT)}`",
        f"- Analytics HTML: `{config.ANALYTICS_HTML.relative_to(config.ROOT)}`",
        f"- Anomaly report: `{config.ANOMALY_REPORT.relative_to(config.ROOT)}`",
        f"- Explanations: `{config.EXPLANATIONS_JSONL.relative_to(config.ROOT)}`",
        "",
        "---",
        "",
        "_Synthetic data only · educational simulation._",
        "",
    ]
    return "\n".join(lines)


def write(metrics: dict, run_meta: dict | None = None) -> Path:
    config.ensure_dirs()
    text = render(metrics, run_meta=run_meta)
    config.DEV_ANALYTICS_MD.write_text(text)
    return config.DEV_ANALYTICS_MD
